# Generated by Django 3.2 on 2021-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.CharField(default='lim', max_length=100),
            preserve_default=False,
        ),
    ]
