# Generated by Django 3.2 on 2021-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
