# Generated by Django 3.2 on 2021-05-26 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210427_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter a brief description about the author', max_length=1000),
            preserve_default=False,
        ),
    ]
