# Generated by Django 3.2 on 2021-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210528_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
    ]
