# Generated by Django 3.2 on 2021-05-28 06:28

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210528_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=stdimage.models.StdImageField(blank=True, help_text='Profile Picture', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
