# Generated by Django 3.2 on 2021-05-28 06:32

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=stdimage.models.StdImageField(blank=True, help_text='Profile Picture', null=True, upload_to='', validators=[stdimage.validators.MaxSizeValidator(328, 268)], verbose_name='Profile Picture'),
        ),
    ]
