# Generated by Django 3.2 on 2021-05-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to=''),
        ),
    ]
